# Configuration for the Local Agent
cloud_url: 'http://localhost:5000' # CHANGE THIS to your deployed cloud app URL
user_id: 'user_...' # Get this from logging into the web UI (needs implementation)
agent_token: 'agent_token_...' # Get this from logging into the web UI (needs implementation)
base_dev_path: '/Users/your_username/Development' # CHANGE THIS to your preferred base folder
# Optional: Add paths to specific tools if not in system PATH (e.g., git_path: /usr/bin/git)